server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  cloud:
    consul:
      host: 192.168.80.71
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false
        # prefer-agent-address: true
        # health-check-path: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health

