server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 再次配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binging整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.80.71
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: consumerA
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2    # 设置心跳的时间间隔默认30秒
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔默认90秒
    instance-id: receive-8803.com # 信息列表时显示主机名称
    prefer-ip-address: true    # 访问路径变为ip地址