server:
  port: 9003
spring:
  application:
    name: cloud-nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.71:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
