server:
  port: 8401
spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.71:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.80.71:8848
            dataId: cloud-sentinel-service
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"
